# Generated by Django 4.0.5 on 2022-06-16 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50)),
                ('home_score', models.IntegerField()),
                ('home_image', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=50)),
                ('away_score', models.IntegerField()),
                ('away_image', models.CharField(max_length=100)),
                ('championship', models.CharField(max_length=100)),
                ('match_hour', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
